# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geo2ENVImet
                                 A QGIS plugin
 This plugin generates ENVI-met model areas from geodata
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-10
        copyright            : (C) 2021 by Helge Simon
        email                : helge.simon@envi-met.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geo2ENVImet class from file Geo2ENVImet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geodata2ENVImet import Geo2ENVImet
    return Geo2ENVImet(iface)
